version: '2'
services:
    seemantovdb-app:
        image: seemantovdb
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://seemantovdb-postgresql:5432/seemantovdb
            - JHIPSTER_CACHE_MEMCACHED_SERVERS=seemantovdb-memcached:11211
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
        ports:
            - 8080:8080
    seemantovdb-postgresql:
        extends:
            file: postgresql.yml
            service: seemantovdb-postgresql
    seemantovdb-memcached:
        extends:
            file: memcached.yml
            service: seemantovdb-memcached
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
